name: Dummy Workflow

on:
  push:
    branches:
      - main

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "✅ Dummy GitHub Action triggered successfully!"
